/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TrustiesIndexImport } from './routes/trusties/index'
import { Route as StaffIndexImport } from './routes/staff/index'
import { Route as SemesterIndexImport } from './routes/semester/index'
import { Route as RoomsIndexImport } from './routes/rooms/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as InventoryIndexImport } from './routes/inventory/index'
import { Route as InstitutesIndexImport } from './routes/institutes/index'
import { Route as DivisionsIndexImport } from './routes/divisions/index'
import { Route as CoursesIndexImport } from './routes/courses/index'
import { Route as TrustiesAddIndexImport } from './routes/trusties/add/index'
import { Route as StaffAddIndexImport } from './routes/staff/add/index'
import { Route as SemesterAddIndexImport } from './routes/semester/add/index'
import { Route as RoomsAddIndexImport } from './routes/rooms/add/index'
import { Route as InventoryAddIndexImport } from './routes/inventory/add/index'
import { Route as InstitutesAddIndexImport } from './routes/institutes/add/index'
import { Route as DivisionsAddIndexImport } from './routes/divisions/add/index'
import { Route as CoursesAddIndexImport } from './routes/courses/add/index'
import { Route as TrustiesEditIdImport } from './routes/trusties/edit/$id'
import { Route as StaffEditIdImport } from './routes/staff/edit/$id'
import { Route as SemesterEditIdImport } from './routes/semester/edit/$id'
import { Route as RoomsEditIdImport } from './routes/rooms/edit/$id'
import { Route as InventoryEditIdImport } from './routes/inventory/edit/$id'
import { Route as InstitutesEditIdImport } from './routes/institutes/edit/$id'
import { Route as DivisionsEditIdImport } from './routes/divisions/edit/$id'
import { Route as CoursesEditIdImport } from './routes/courses/edit/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TrustiesIndexRoute = TrustiesIndexImport.update({
  id: '/trusties/',
  path: '/trusties/',
  getParentRoute: () => rootRoute,
} as any)

const StaffIndexRoute = StaffIndexImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRoute,
} as any)

const SemesterIndexRoute = SemesterIndexImport.update({
  id: '/semester/',
  path: '/semester/',
  getParentRoute: () => rootRoute,
} as any)

const RoomsIndexRoute = RoomsIndexImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const InventoryIndexRoute = InventoryIndexImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRoute,
} as any)

const InstitutesIndexRoute = InstitutesIndexImport.update({
  id: '/institutes/',
  path: '/institutes/',
  getParentRoute: () => rootRoute,
} as any)

const DivisionsIndexRoute = DivisionsIndexImport.update({
  id: '/divisions/',
  path: '/divisions/',
  getParentRoute: () => rootRoute,
} as any)

const CoursesIndexRoute = CoursesIndexImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRoute,
} as any)

const TrustiesAddIndexRoute = TrustiesAddIndexImport.update({
  id: '/trusties/add/',
  path: '/trusties/add/',
  getParentRoute: () => rootRoute,
} as any)

const StaffAddIndexRoute = StaffAddIndexImport.update({
  id: '/staff/add/',
  path: '/staff/add/',
  getParentRoute: () => rootRoute,
} as any)

const SemesterAddIndexRoute = SemesterAddIndexImport.update({
  id: '/semester/add/',
  path: '/semester/add/',
  getParentRoute: () => rootRoute,
} as any)

const RoomsAddIndexRoute = RoomsAddIndexImport.update({
  id: '/rooms/add/',
  path: '/rooms/add/',
  getParentRoute: () => rootRoute,
} as any)

const InventoryAddIndexRoute = InventoryAddIndexImport.update({
  id: '/inventory/add/',
  path: '/inventory/add/',
  getParentRoute: () => rootRoute,
} as any)

const InstitutesAddIndexRoute = InstitutesAddIndexImport.update({
  id: '/institutes/add/',
  path: '/institutes/add/',
  getParentRoute: () => rootRoute,
} as any)

const DivisionsAddIndexRoute = DivisionsAddIndexImport.update({
  id: '/divisions/add/',
  path: '/divisions/add/',
  getParentRoute: () => rootRoute,
} as any)

const CoursesAddIndexRoute = CoursesAddIndexImport.update({
  id: '/courses/add/',
  path: '/courses/add/',
  getParentRoute: () => rootRoute,
} as any)

const TrustiesEditIdRoute = TrustiesEditIdImport.update({
  id: '/trusties/edit/$id',
  path: '/trusties/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const StaffEditIdRoute = StaffEditIdImport.update({
  id: '/staff/edit/$id',
  path: '/staff/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const SemesterEditIdRoute = SemesterEditIdImport.update({
  id: '/semester/edit/$id',
  path: '/semester/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const RoomsEditIdRoute = RoomsEditIdImport.update({
  id: '/rooms/edit/$id',
  path: '/rooms/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const InventoryEditIdRoute = InventoryEditIdImport.update({
  id: '/inventory/edit/$id',
  path: '/inventory/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const InstitutesEditIdRoute = InstitutesEditIdImport.update({
  id: '/institutes/edit/$id',
  path: '/institutes/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const DivisionsEditIdRoute = DivisionsEditIdImport.update({
  id: '/divisions/edit/$id',
  path: '/divisions/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const CoursesEditIdRoute = CoursesEditIdImport.update({
  id: '/courses/edit/$id',
  path: '/courses/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexImport
      parentRoute: typeof rootRoute
    }
    '/divisions/': {
      id: '/divisions/'
      path: '/divisions'
      fullPath: '/divisions'
      preLoaderRoute: typeof DivisionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/institutes/': {
      id: '/institutes/'
      path: '/institutes'
      fullPath: '/institutes'
      preLoaderRoute: typeof InstitutesIndexImport
      parentRoute: typeof rootRoute
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsIndexImport
      parentRoute: typeof rootRoute
    }
    '/semester/': {
      id: '/semester/'
      path: '/semester'
      fullPath: '/semester'
      preLoaderRoute: typeof SemesterIndexImport
      parentRoute: typeof rootRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffIndexImport
      parentRoute: typeof rootRoute
    }
    '/trusties/': {
      id: '/trusties/'
      path: '/trusties'
      fullPath: '/trusties'
      preLoaderRoute: typeof TrustiesIndexImport
      parentRoute: typeof rootRoute
    }
    '/courses/edit/$id': {
      id: '/courses/edit/$id'
      path: '/courses/edit/$id'
      fullPath: '/courses/edit/$id'
      preLoaderRoute: typeof CoursesEditIdImport
      parentRoute: typeof rootRoute
    }
    '/divisions/edit/$id': {
      id: '/divisions/edit/$id'
      path: '/divisions/edit/$id'
      fullPath: '/divisions/edit/$id'
      preLoaderRoute: typeof DivisionsEditIdImport
      parentRoute: typeof rootRoute
    }
    '/institutes/edit/$id': {
      id: '/institutes/edit/$id'
      path: '/institutes/edit/$id'
      fullPath: '/institutes/edit/$id'
      preLoaderRoute: typeof InstitutesEditIdImport
      parentRoute: typeof rootRoute
    }
    '/inventory/edit/$id': {
      id: '/inventory/edit/$id'
      path: '/inventory/edit/$id'
      fullPath: '/inventory/edit/$id'
      preLoaderRoute: typeof InventoryEditIdImport
      parentRoute: typeof rootRoute
    }
    '/rooms/edit/$id': {
      id: '/rooms/edit/$id'
      path: '/rooms/edit/$id'
      fullPath: '/rooms/edit/$id'
      preLoaderRoute: typeof RoomsEditIdImport
      parentRoute: typeof rootRoute
    }
    '/semester/edit/$id': {
      id: '/semester/edit/$id'
      path: '/semester/edit/$id'
      fullPath: '/semester/edit/$id'
      preLoaderRoute: typeof SemesterEditIdImport
      parentRoute: typeof rootRoute
    }
    '/staff/edit/$id': {
      id: '/staff/edit/$id'
      path: '/staff/edit/$id'
      fullPath: '/staff/edit/$id'
      preLoaderRoute: typeof StaffEditIdImport
      parentRoute: typeof rootRoute
    }
    '/trusties/edit/$id': {
      id: '/trusties/edit/$id'
      path: '/trusties/edit/$id'
      fullPath: '/trusties/edit/$id'
      preLoaderRoute: typeof TrustiesEditIdImport
      parentRoute: typeof rootRoute
    }
    '/courses/add/': {
      id: '/courses/add/'
      path: '/courses/add'
      fullPath: '/courses/add'
      preLoaderRoute: typeof CoursesAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/divisions/add/': {
      id: '/divisions/add/'
      path: '/divisions/add'
      fullPath: '/divisions/add'
      preLoaderRoute: typeof DivisionsAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/institutes/add/': {
      id: '/institutes/add/'
      path: '/institutes/add'
      fullPath: '/institutes/add'
      preLoaderRoute: typeof InstitutesAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/inventory/add/': {
      id: '/inventory/add/'
      path: '/inventory/add'
      fullPath: '/inventory/add'
      preLoaderRoute: typeof InventoryAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/rooms/add/': {
      id: '/rooms/add/'
      path: '/rooms/add'
      fullPath: '/rooms/add'
      preLoaderRoute: typeof RoomsAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/semester/add/': {
      id: '/semester/add/'
      path: '/semester/add'
      fullPath: '/semester/add'
      preLoaderRoute: typeof SemesterAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/staff/add/': {
      id: '/staff/add/'
      path: '/staff/add'
      fullPath: '/staff/add'
      preLoaderRoute: typeof StaffAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/trusties/add/': {
      id: '/trusties/add/'
      path: '/trusties/add'
      fullPath: '/trusties/add'
      preLoaderRoute: typeof TrustiesAddIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesIndexRoute
  '/divisions': typeof DivisionsIndexRoute
  '/institutes': typeof InstitutesIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/login': typeof LoginIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/semester': typeof SemesterIndexRoute
  '/staff': typeof StaffIndexRoute
  '/trusties': typeof TrustiesIndexRoute
  '/courses/edit/$id': typeof CoursesEditIdRoute
  '/divisions/edit/$id': typeof DivisionsEditIdRoute
  '/institutes/edit/$id': typeof InstitutesEditIdRoute
  '/inventory/edit/$id': typeof InventoryEditIdRoute
  '/rooms/edit/$id': typeof RoomsEditIdRoute
  '/semester/edit/$id': typeof SemesterEditIdRoute
  '/staff/edit/$id': typeof StaffEditIdRoute
  '/trusties/edit/$id': typeof TrustiesEditIdRoute
  '/courses/add': typeof CoursesAddIndexRoute
  '/divisions/add': typeof DivisionsAddIndexRoute
  '/institutes/add': typeof InstitutesAddIndexRoute
  '/inventory/add': typeof InventoryAddIndexRoute
  '/rooms/add': typeof RoomsAddIndexRoute
  '/semester/add': typeof SemesterAddIndexRoute
  '/staff/add': typeof StaffAddIndexRoute
  '/trusties/add': typeof TrustiesAddIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesIndexRoute
  '/divisions': typeof DivisionsIndexRoute
  '/institutes': typeof InstitutesIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/login': typeof LoginIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/semester': typeof SemesterIndexRoute
  '/staff': typeof StaffIndexRoute
  '/trusties': typeof TrustiesIndexRoute
  '/courses/edit/$id': typeof CoursesEditIdRoute
  '/divisions/edit/$id': typeof DivisionsEditIdRoute
  '/institutes/edit/$id': typeof InstitutesEditIdRoute
  '/inventory/edit/$id': typeof InventoryEditIdRoute
  '/rooms/edit/$id': typeof RoomsEditIdRoute
  '/semester/edit/$id': typeof SemesterEditIdRoute
  '/staff/edit/$id': typeof StaffEditIdRoute
  '/trusties/edit/$id': typeof TrustiesEditIdRoute
  '/courses/add': typeof CoursesAddIndexRoute
  '/divisions/add': typeof DivisionsAddIndexRoute
  '/institutes/add': typeof InstitutesAddIndexRoute
  '/inventory/add': typeof InventoryAddIndexRoute
  '/rooms/add': typeof RoomsAddIndexRoute
  '/semester/add': typeof SemesterAddIndexRoute
  '/staff/add': typeof StaffAddIndexRoute
  '/trusties/add': typeof TrustiesAddIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/divisions/': typeof DivisionsIndexRoute
  '/institutes/': typeof InstitutesIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/login/': typeof LoginIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/semester/': typeof SemesterIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/trusties/': typeof TrustiesIndexRoute
  '/courses/edit/$id': typeof CoursesEditIdRoute
  '/divisions/edit/$id': typeof DivisionsEditIdRoute
  '/institutes/edit/$id': typeof InstitutesEditIdRoute
  '/inventory/edit/$id': typeof InventoryEditIdRoute
  '/rooms/edit/$id': typeof RoomsEditIdRoute
  '/semester/edit/$id': typeof SemesterEditIdRoute
  '/staff/edit/$id': typeof StaffEditIdRoute
  '/trusties/edit/$id': typeof TrustiesEditIdRoute
  '/courses/add/': typeof CoursesAddIndexRoute
  '/divisions/add/': typeof DivisionsAddIndexRoute
  '/institutes/add/': typeof InstitutesAddIndexRoute
  '/inventory/add/': typeof InventoryAddIndexRoute
  '/rooms/add/': typeof RoomsAddIndexRoute
  '/semester/add/': typeof SemesterAddIndexRoute
  '/staff/add/': typeof StaffAddIndexRoute
  '/trusties/add/': typeof TrustiesAddIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/divisions'
    | '/institutes'
    | '/inventory'
    | '/login'
    | '/rooms'
    | '/semester'
    | '/staff'
    | '/trusties'
    | '/courses/edit/$id'
    | '/divisions/edit/$id'
    | '/institutes/edit/$id'
    | '/inventory/edit/$id'
    | '/rooms/edit/$id'
    | '/semester/edit/$id'
    | '/staff/edit/$id'
    | '/trusties/edit/$id'
    | '/courses/add'
    | '/divisions/add'
    | '/institutes/add'
    | '/inventory/add'
    | '/rooms/add'
    | '/semester/add'
    | '/staff/add'
    | '/trusties/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/divisions'
    | '/institutes'
    | '/inventory'
    | '/login'
    | '/rooms'
    | '/semester'
    | '/staff'
    | '/trusties'
    | '/courses/edit/$id'
    | '/divisions/edit/$id'
    | '/institutes/edit/$id'
    | '/inventory/edit/$id'
    | '/rooms/edit/$id'
    | '/semester/edit/$id'
    | '/staff/edit/$id'
    | '/trusties/edit/$id'
    | '/courses/add'
    | '/divisions/add'
    | '/institutes/add'
    | '/inventory/add'
    | '/rooms/add'
    | '/semester/add'
    | '/staff/add'
    | '/trusties/add'
  id:
    | '__root__'
    | '/'
    | '/courses/'
    | '/divisions/'
    | '/institutes/'
    | '/inventory/'
    | '/login/'
    | '/rooms/'
    | '/semester/'
    | '/staff/'
    | '/trusties/'
    | '/courses/edit/$id'
    | '/divisions/edit/$id'
    | '/institutes/edit/$id'
    | '/inventory/edit/$id'
    | '/rooms/edit/$id'
    | '/semester/edit/$id'
    | '/staff/edit/$id'
    | '/trusties/edit/$id'
    | '/courses/add/'
    | '/divisions/add/'
    | '/institutes/add/'
    | '/inventory/add/'
    | '/rooms/add/'
    | '/semester/add/'
    | '/staff/add/'
    | '/trusties/add/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  DivisionsIndexRoute: typeof DivisionsIndexRoute
  InstitutesIndexRoute: typeof InstitutesIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  SemesterIndexRoute: typeof SemesterIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  TrustiesIndexRoute: typeof TrustiesIndexRoute
  CoursesEditIdRoute: typeof CoursesEditIdRoute
  DivisionsEditIdRoute: typeof DivisionsEditIdRoute
  InstitutesEditIdRoute: typeof InstitutesEditIdRoute
  InventoryEditIdRoute: typeof InventoryEditIdRoute
  RoomsEditIdRoute: typeof RoomsEditIdRoute
  SemesterEditIdRoute: typeof SemesterEditIdRoute
  StaffEditIdRoute: typeof StaffEditIdRoute
  TrustiesEditIdRoute: typeof TrustiesEditIdRoute
  CoursesAddIndexRoute: typeof CoursesAddIndexRoute
  DivisionsAddIndexRoute: typeof DivisionsAddIndexRoute
  InstitutesAddIndexRoute: typeof InstitutesAddIndexRoute
  InventoryAddIndexRoute: typeof InventoryAddIndexRoute
  RoomsAddIndexRoute: typeof RoomsAddIndexRoute
  SemesterAddIndexRoute: typeof SemesterAddIndexRoute
  StaffAddIndexRoute: typeof StaffAddIndexRoute
  TrustiesAddIndexRoute: typeof TrustiesAddIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  DivisionsIndexRoute: DivisionsIndexRoute,
  InstitutesIndexRoute: InstitutesIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  SemesterIndexRoute: SemesterIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  TrustiesIndexRoute: TrustiesIndexRoute,
  CoursesEditIdRoute: CoursesEditIdRoute,
  DivisionsEditIdRoute: DivisionsEditIdRoute,
  InstitutesEditIdRoute: InstitutesEditIdRoute,
  InventoryEditIdRoute: InventoryEditIdRoute,
  RoomsEditIdRoute: RoomsEditIdRoute,
  SemesterEditIdRoute: SemesterEditIdRoute,
  StaffEditIdRoute: StaffEditIdRoute,
  TrustiesEditIdRoute: TrustiesEditIdRoute,
  CoursesAddIndexRoute: CoursesAddIndexRoute,
  DivisionsAddIndexRoute: DivisionsAddIndexRoute,
  InstitutesAddIndexRoute: InstitutesAddIndexRoute,
  InventoryAddIndexRoute: InventoryAddIndexRoute,
  RoomsAddIndexRoute: RoomsAddIndexRoute,
  SemesterAddIndexRoute: SemesterAddIndexRoute,
  StaffAddIndexRoute: StaffAddIndexRoute,
  TrustiesAddIndexRoute: TrustiesAddIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/courses/",
        "/divisions/",
        "/institutes/",
        "/inventory/",
        "/login/",
        "/rooms/",
        "/semester/",
        "/staff/",
        "/trusties/",
        "/courses/edit/$id",
        "/divisions/edit/$id",
        "/institutes/edit/$id",
        "/inventory/edit/$id",
        "/rooms/edit/$id",
        "/semester/edit/$id",
        "/staff/edit/$id",
        "/trusties/edit/$id",
        "/courses/add/",
        "/divisions/add/",
        "/institutes/add/",
        "/inventory/add/",
        "/rooms/add/",
        "/semester/add/",
        "/staff/add/",
        "/trusties/add/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/courses/": {
      "filePath": "courses/index.tsx"
    },
    "/divisions/": {
      "filePath": "divisions/index.tsx"
    },
    "/institutes/": {
      "filePath": "institutes/index.tsx"
    },
    "/inventory/": {
      "filePath": "inventory/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/rooms/": {
      "filePath": "rooms/index.tsx"
    },
    "/semester/": {
      "filePath": "semester/index.tsx"
    },
    "/staff/": {
      "filePath": "staff/index.tsx"
    },
    "/trusties/": {
      "filePath": "trusties/index.tsx"
    },
    "/courses/edit/$id": {
      "filePath": "courses/edit/$id.tsx"
    },
    "/divisions/edit/$id": {
      "filePath": "divisions/edit/$id.tsx"
    },
    "/institutes/edit/$id": {
      "filePath": "institutes/edit/$id.tsx"
    },
    "/inventory/edit/$id": {
      "filePath": "inventory/edit/$id.tsx"
    },
    "/rooms/edit/$id": {
      "filePath": "rooms/edit/$id.tsx"
    },
    "/semester/edit/$id": {
      "filePath": "semester/edit/$id.tsx"
    },
    "/staff/edit/$id": {
      "filePath": "staff/edit/$id.tsx"
    },
    "/trusties/edit/$id": {
      "filePath": "trusties/edit/$id.tsx"
    },
    "/courses/add/": {
      "filePath": "courses/add/index.tsx"
    },
    "/divisions/add/": {
      "filePath": "divisions/add/index.tsx"
    },
    "/institutes/add/": {
      "filePath": "institutes/add/index.tsx"
    },
    "/inventory/add/": {
      "filePath": "inventory/add/index.tsx"
    },
    "/rooms/add/": {
      "filePath": "rooms/add/index.tsx"
    },
    "/semester/add/": {
      "filePath": "semester/add/index.tsx"
    },
    "/staff/add/": {
      "filePath": "staff/add/index.tsx"
    },
    "/trusties/add/": {
      "filePath": "trusties/add/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
