/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TrustiesIndexImport } from './routes/trusties/index'
import { Route as SubjectsIndexImport } from './routes/subjects/index'
import { Route as StudentsIndexImport } from './routes/students/index'
import { Route as StaffdashboardIndexImport } from './routes/staffdashboard/index'
import { Route as StaffIndexImport } from './routes/staff/index'
import { Route as SemesterIndexImport } from './routes/semester/index'
import { Route as RootdashboardIndexImport } from './routes/rootdashboard/index'
import { Route as RoomsIndexImport } from './routes/rooms/index'
import { Route as MemberdashboardIndexImport } from './routes/memberdashboard/index'
import { Route as MeetingsIndexImport } from './routes/meetings/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as InventoryIndexImport } from './routes/inventory/index'
import { Route as InstitutesIndexImport } from './routes/institutes/index'
import { Route as EventsIndexImport } from './routes/events/index'
import { Route as DivisionsIndexImport } from './routes/divisions/index'
import { Route as CoursesIndexImport } from './routes/courses/index'
import { Route as ComplaintsIndexImport } from './routes/complaints/index'
import { Route as CommitteeIndexImport } from './routes/committee/index'
import { Route as CashiersIndexImport } from './routes/cashiers/index'
import { Route as CalenderIndexImport } from './routes/calender/index'
import { Route as AdmissionsIndexImport } from './routes/admissions/index'
import { Route as TrustiesAddIndexImport } from './routes/trusties/add/index'
import { Route as SubjectsAddIndexImport } from './routes/subjects/add/index'
import { Route as StudentsAddIndexImport } from './routes/students/add/index'
import { Route as StaffAddIndexImport } from './routes/staff/add/index'
import { Route as SemesterAddIndexImport } from './routes/semester/add/index'
import { Route as RoomsAddIndexImport } from './routes/rooms/add/index'
import { Route as MeetingsAddIndexImport } from './routes/meetings/add/index'
import { Route as InventoryAddIndexImport } from './routes/inventory/add/index'
import { Route as InstitutesAddIndexImport } from './routes/institutes/add/index'
import { Route as EventsAddIndexImport } from './routes/events/add/index'
import { Route as DivisionsAddIndexImport } from './routes/divisions/add/index'
import { Route as CoursesAddIndexImport } from './routes/courses/add/index'
import { Route as ComplaintsAddIndexImport } from './routes/complaints/add/index'
import { Route as CommitteeAddIndexImport } from './routes/committee/add/index'
import { Route as CashiersAddIndexImport } from './routes/cashiers/add/index'
import { Route as AdmissionsAddIndexImport } from './routes/admissions/add/index'
import { Route as TrustiesEditIdImport } from './routes/trusties/edit/$id'
import { Route as SubjectsEditIdImport } from './routes/subjects/edit/$id'
import { Route as StudentsEditIdImport } from './routes/students/edit/$id'
import { Route as StaffEditIdImport } from './routes/staff/edit/$id'
import { Route as SemesterEditIdImport } from './routes/semester/edit/$id'
import { Route as RoomsEditIdImport } from './routes/rooms/edit/$id'
import { Route as MeetingsEditIdImport } from './routes/meetings/edit/$id'
import { Route as InventoryEditIdImport } from './routes/inventory/edit/$id'
import { Route as InstitutesEditIdImport } from './routes/institutes/edit/$id'
import { Route as EventsEditIdImport } from './routes/events/edit/$id'
import { Route as DivisionsEditIdImport } from './routes/divisions/edit/$id'
import { Route as CoursesEditIdImport } from './routes/courses/edit/$id'
import { Route as ComplaintsEditIdImport } from './routes/complaints/edit/$id'
import { Route as CommitteeEditIdImport } from './routes/committee/edit/$id'
import { Route as CashiersEditIdImport } from './routes/cashiers/edit/$id'
import { Route as AdmissionsEditIdImport } from './routes/admissions/edit/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TrustiesIndexRoute = TrustiesIndexImport.update({
  id: '/trusties/',
  path: '/trusties/',
  getParentRoute: () => rootRoute,
} as any)

const SubjectsIndexRoute = SubjectsIndexImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRoute,
} as any)

const StudentsIndexRoute = StudentsIndexImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRoute,
} as any)

const StaffdashboardIndexRoute = StaffdashboardIndexImport.update({
  id: '/staffdashboard/',
  path: '/staffdashboard/',
  getParentRoute: () => rootRoute,
} as any)

const StaffIndexRoute = StaffIndexImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRoute,
} as any)

const SemesterIndexRoute = SemesterIndexImport.update({
  id: '/semester/',
  path: '/semester/',
  getParentRoute: () => rootRoute,
} as any)

const RootdashboardIndexRoute = RootdashboardIndexImport.update({
  id: '/rootdashboard/',
  path: '/rootdashboard/',
  getParentRoute: () => rootRoute,
} as any)

const RoomsIndexRoute = RoomsIndexImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRoute,
} as any)

const MemberdashboardIndexRoute = MemberdashboardIndexImport.update({
  id: '/memberdashboard/',
  path: '/memberdashboard/',
  getParentRoute: () => rootRoute,
} as any)

const MeetingsIndexRoute = MeetingsIndexImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const InventoryIndexRoute = InventoryIndexImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRoute,
} as any)

const InstitutesIndexRoute = InstitutesIndexImport.update({
  id: '/institutes/',
  path: '/institutes/',
  getParentRoute: () => rootRoute,
} as any)

const EventsIndexRoute = EventsIndexImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRoute,
} as any)

const DivisionsIndexRoute = DivisionsIndexImport.update({
  id: '/divisions/',
  path: '/divisions/',
  getParentRoute: () => rootRoute,
} as any)

const CoursesIndexRoute = CoursesIndexImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRoute,
} as any)

const ComplaintsIndexRoute = ComplaintsIndexImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => rootRoute,
} as any)

const CommitteeIndexRoute = CommitteeIndexImport.update({
  id: '/committee/',
  path: '/committee/',
  getParentRoute: () => rootRoute,
} as any)

const CashiersIndexRoute = CashiersIndexImport.update({
  id: '/cashiers/',
  path: '/cashiers/',
  getParentRoute: () => rootRoute,
} as any)

const CalenderIndexRoute = CalenderIndexImport.update({
  id: '/calender/',
  path: '/calender/',
  getParentRoute: () => rootRoute,
} as any)

const AdmissionsIndexRoute = AdmissionsIndexImport.update({
  id: '/admissions/',
  path: '/admissions/',
  getParentRoute: () => rootRoute,
} as any)

const TrustiesAddIndexRoute = TrustiesAddIndexImport.update({
  id: '/trusties/add/',
  path: '/trusties/add/',
  getParentRoute: () => rootRoute,
} as any)

const SubjectsAddIndexRoute = SubjectsAddIndexImport.update({
  id: '/subjects/add/',
  path: '/subjects/add/',
  getParentRoute: () => rootRoute,
} as any)

const StudentsAddIndexRoute = StudentsAddIndexImport.update({
  id: '/students/add/',
  path: '/students/add/',
  getParentRoute: () => rootRoute,
} as any)

const StaffAddIndexRoute = StaffAddIndexImport.update({
  id: '/staff/add/',
  path: '/staff/add/',
  getParentRoute: () => rootRoute,
} as any)

const SemesterAddIndexRoute = SemesterAddIndexImport.update({
  id: '/semester/add/',
  path: '/semester/add/',
  getParentRoute: () => rootRoute,
} as any)

const RoomsAddIndexRoute = RoomsAddIndexImport.update({
  id: '/rooms/add/',
  path: '/rooms/add/',
  getParentRoute: () => rootRoute,
} as any)

const MeetingsAddIndexRoute = MeetingsAddIndexImport.update({
  id: '/meetings/add/',
  path: '/meetings/add/',
  getParentRoute: () => rootRoute,
} as any)

const InventoryAddIndexRoute = InventoryAddIndexImport.update({
  id: '/inventory/add/',
  path: '/inventory/add/',
  getParentRoute: () => rootRoute,
} as any)

const InstitutesAddIndexRoute = InstitutesAddIndexImport.update({
  id: '/institutes/add/',
  path: '/institutes/add/',
  getParentRoute: () => rootRoute,
} as any)

const EventsAddIndexRoute = EventsAddIndexImport.update({
  id: '/events/add/',
  path: '/events/add/',
  getParentRoute: () => rootRoute,
} as any)

const DivisionsAddIndexRoute = DivisionsAddIndexImport.update({
  id: '/divisions/add/',
  path: '/divisions/add/',
  getParentRoute: () => rootRoute,
} as any)

const CoursesAddIndexRoute = CoursesAddIndexImport.update({
  id: '/courses/add/',
  path: '/courses/add/',
  getParentRoute: () => rootRoute,
} as any)

const ComplaintsAddIndexRoute = ComplaintsAddIndexImport.update({
  id: '/complaints/add/',
  path: '/complaints/add/',
  getParentRoute: () => rootRoute,
} as any)

const CommitteeAddIndexRoute = CommitteeAddIndexImport.update({
  id: '/committee/add/',
  path: '/committee/add/',
  getParentRoute: () => rootRoute,
} as any)

const CashiersAddIndexRoute = CashiersAddIndexImport.update({
  id: '/cashiers/add/',
  path: '/cashiers/add/',
  getParentRoute: () => rootRoute,
} as any)

const AdmissionsAddIndexRoute = AdmissionsAddIndexImport.update({
  id: '/admissions/add/',
  path: '/admissions/add/',
  getParentRoute: () => rootRoute,
} as any)

const TrustiesEditIdRoute = TrustiesEditIdImport.update({
  id: '/trusties/edit/$id',
  path: '/trusties/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const SubjectsEditIdRoute = SubjectsEditIdImport.update({
  id: '/subjects/edit/$id',
  path: '/subjects/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const StudentsEditIdRoute = StudentsEditIdImport.update({
  id: '/students/edit/$id',
  path: '/students/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const StaffEditIdRoute = StaffEditIdImport.update({
  id: '/staff/edit/$id',
  path: '/staff/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const SemesterEditIdRoute = SemesterEditIdImport.update({
  id: '/semester/edit/$id',
  path: '/semester/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const RoomsEditIdRoute = RoomsEditIdImport.update({
  id: '/rooms/edit/$id',
  path: '/rooms/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const MeetingsEditIdRoute = MeetingsEditIdImport.update({
  id: '/meetings/edit/$id',
  path: '/meetings/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const InventoryEditIdRoute = InventoryEditIdImport.update({
  id: '/inventory/edit/$id',
  path: '/inventory/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const InstitutesEditIdRoute = InstitutesEditIdImport.update({
  id: '/institutes/edit/$id',
  path: '/institutes/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const EventsEditIdRoute = EventsEditIdImport.update({
  id: '/events/edit/$id',
  path: '/events/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const DivisionsEditIdRoute = DivisionsEditIdImport.update({
  id: '/divisions/edit/$id',
  path: '/divisions/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const CoursesEditIdRoute = CoursesEditIdImport.update({
  id: '/courses/edit/$id',
  path: '/courses/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const ComplaintsEditIdRoute = ComplaintsEditIdImport.update({
  id: '/complaints/edit/$id',
  path: '/complaints/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const CommitteeEditIdRoute = CommitteeEditIdImport.update({
  id: '/committee/edit/$id',
  path: '/committee/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const CashiersEditIdRoute = CashiersEditIdImport.update({
  id: '/cashiers/edit/$id',
  path: '/cashiers/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const AdmissionsEditIdRoute = AdmissionsEditIdImport.update({
  id: '/admissions/edit/$id',
  path: '/admissions/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admissions/': {
      id: '/admissions/'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/calender/': {
      id: '/calender/'
      path: '/calender'
      fullPath: '/calender'
      preLoaderRoute: typeof CalenderIndexImport
      parentRoute: typeof rootRoute
    }
    '/cashiers/': {
      id: '/cashiers/'
      path: '/cashiers'
      fullPath: '/cashiers'
      preLoaderRoute: typeof CashiersIndexImport
      parentRoute: typeof rootRoute
    }
    '/committee/': {
      id: '/committee/'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof CommitteeIndexImport
      parentRoute: typeof rootRoute
    }
    '/complaints/': {
      id: '/complaints/'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsIndexImport
      parentRoute: typeof rootRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexImport
      parentRoute: typeof rootRoute
    }
    '/divisions/': {
      id: '/divisions/'
      path: '/divisions'
      fullPath: '/divisions'
      preLoaderRoute: typeof DivisionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexImport
      parentRoute: typeof rootRoute
    }
    '/institutes/': {
      id: '/institutes/'
      path: '/institutes'
      fullPath: '/institutes'
      preLoaderRoute: typeof InstitutesIndexImport
      parentRoute: typeof rootRoute
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/meetings/': {
      id: '/meetings/'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/memberdashboard/': {
      id: '/memberdashboard/'
      path: '/memberdashboard'
      fullPath: '/memberdashboard'
      preLoaderRoute: typeof MemberdashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsIndexImport
      parentRoute: typeof rootRoute
    }
    '/rootdashboard/': {
      id: '/rootdashboard/'
      path: '/rootdashboard'
      fullPath: '/rootdashboard'
      preLoaderRoute: typeof RootdashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/semester/': {
      id: '/semester/'
      path: '/semester'
      fullPath: '/semester'
      preLoaderRoute: typeof SemesterIndexImport
      parentRoute: typeof rootRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffIndexImport
      parentRoute: typeof rootRoute
    }
    '/staffdashboard/': {
      id: '/staffdashboard/'
      path: '/staffdashboard'
      fullPath: '/staffdashboard'
      preLoaderRoute: typeof StaffdashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsIndexImport
      parentRoute: typeof rootRoute
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/trusties/': {
      id: '/trusties/'
      path: '/trusties'
      fullPath: '/trusties'
      preLoaderRoute: typeof TrustiesIndexImport
      parentRoute: typeof rootRoute
    }
    '/admissions/edit/$id': {
      id: '/admissions/edit/$id'
      path: '/admissions/edit/$id'
      fullPath: '/admissions/edit/$id'
      preLoaderRoute: typeof AdmissionsEditIdImport
      parentRoute: typeof rootRoute
    }
    '/cashiers/edit/$id': {
      id: '/cashiers/edit/$id'
      path: '/cashiers/edit/$id'
      fullPath: '/cashiers/edit/$id'
      preLoaderRoute: typeof CashiersEditIdImport
      parentRoute: typeof rootRoute
    }
    '/committee/edit/$id': {
      id: '/committee/edit/$id'
      path: '/committee/edit/$id'
      fullPath: '/committee/edit/$id'
      preLoaderRoute: typeof CommitteeEditIdImport
      parentRoute: typeof rootRoute
    }
    '/complaints/edit/$id': {
      id: '/complaints/edit/$id'
      path: '/complaints/edit/$id'
      fullPath: '/complaints/edit/$id'
      preLoaderRoute: typeof ComplaintsEditIdImport
      parentRoute: typeof rootRoute
    }
    '/courses/edit/$id': {
      id: '/courses/edit/$id'
      path: '/courses/edit/$id'
      fullPath: '/courses/edit/$id'
      preLoaderRoute: typeof CoursesEditIdImport
      parentRoute: typeof rootRoute
    }
    '/divisions/edit/$id': {
      id: '/divisions/edit/$id'
      path: '/divisions/edit/$id'
      fullPath: '/divisions/edit/$id'
      preLoaderRoute: typeof DivisionsEditIdImport
      parentRoute: typeof rootRoute
    }
    '/events/edit/$id': {
      id: '/events/edit/$id'
      path: '/events/edit/$id'
      fullPath: '/events/edit/$id'
      preLoaderRoute: typeof EventsEditIdImport
      parentRoute: typeof rootRoute
    }
    '/institutes/edit/$id': {
      id: '/institutes/edit/$id'
      path: '/institutes/edit/$id'
      fullPath: '/institutes/edit/$id'
      preLoaderRoute: typeof InstitutesEditIdImport
      parentRoute: typeof rootRoute
    }
    '/inventory/edit/$id': {
      id: '/inventory/edit/$id'
      path: '/inventory/edit/$id'
      fullPath: '/inventory/edit/$id'
      preLoaderRoute: typeof InventoryEditIdImport
      parentRoute: typeof rootRoute
    }
    '/meetings/edit/$id': {
      id: '/meetings/edit/$id'
      path: '/meetings/edit/$id'
      fullPath: '/meetings/edit/$id'
      preLoaderRoute: typeof MeetingsEditIdImport
      parentRoute: typeof rootRoute
    }
    '/rooms/edit/$id': {
      id: '/rooms/edit/$id'
      path: '/rooms/edit/$id'
      fullPath: '/rooms/edit/$id'
      preLoaderRoute: typeof RoomsEditIdImport
      parentRoute: typeof rootRoute
    }
    '/semester/edit/$id': {
      id: '/semester/edit/$id'
      path: '/semester/edit/$id'
      fullPath: '/semester/edit/$id'
      preLoaderRoute: typeof SemesterEditIdImport
      parentRoute: typeof rootRoute
    }
    '/staff/edit/$id': {
      id: '/staff/edit/$id'
      path: '/staff/edit/$id'
      fullPath: '/staff/edit/$id'
      preLoaderRoute: typeof StaffEditIdImport
      parentRoute: typeof rootRoute
    }
    '/students/edit/$id': {
      id: '/students/edit/$id'
      path: '/students/edit/$id'
      fullPath: '/students/edit/$id'
      preLoaderRoute: typeof StudentsEditIdImport
      parentRoute: typeof rootRoute
    }
    '/subjects/edit/$id': {
      id: '/subjects/edit/$id'
      path: '/subjects/edit/$id'
      fullPath: '/subjects/edit/$id'
      preLoaderRoute: typeof SubjectsEditIdImport
      parentRoute: typeof rootRoute
    }
    '/trusties/edit/$id': {
      id: '/trusties/edit/$id'
      path: '/trusties/edit/$id'
      fullPath: '/trusties/edit/$id'
      preLoaderRoute: typeof TrustiesEditIdImport
      parentRoute: typeof rootRoute
    }
    '/admissions/add/': {
      id: '/admissions/add/'
      path: '/admissions/add'
      fullPath: '/admissions/add'
      preLoaderRoute: typeof AdmissionsAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/cashiers/add/': {
      id: '/cashiers/add/'
      path: '/cashiers/add'
      fullPath: '/cashiers/add'
      preLoaderRoute: typeof CashiersAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/committee/add/': {
      id: '/committee/add/'
      path: '/committee/add'
      fullPath: '/committee/add'
      preLoaderRoute: typeof CommitteeAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/complaints/add/': {
      id: '/complaints/add/'
      path: '/complaints/add'
      fullPath: '/complaints/add'
      preLoaderRoute: typeof ComplaintsAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/courses/add/': {
      id: '/courses/add/'
      path: '/courses/add'
      fullPath: '/courses/add'
      preLoaderRoute: typeof CoursesAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/divisions/add/': {
      id: '/divisions/add/'
      path: '/divisions/add'
      fullPath: '/divisions/add'
      preLoaderRoute: typeof DivisionsAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/events/add/': {
      id: '/events/add/'
      path: '/events/add'
      fullPath: '/events/add'
      preLoaderRoute: typeof EventsAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/institutes/add/': {
      id: '/institutes/add/'
      path: '/institutes/add'
      fullPath: '/institutes/add'
      preLoaderRoute: typeof InstitutesAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/inventory/add/': {
      id: '/inventory/add/'
      path: '/inventory/add'
      fullPath: '/inventory/add'
      preLoaderRoute: typeof InventoryAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/meetings/add/': {
      id: '/meetings/add/'
      path: '/meetings/add'
      fullPath: '/meetings/add'
      preLoaderRoute: typeof MeetingsAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/rooms/add/': {
      id: '/rooms/add/'
      path: '/rooms/add'
      fullPath: '/rooms/add'
      preLoaderRoute: typeof RoomsAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/semester/add/': {
      id: '/semester/add/'
      path: '/semester/add'
      fullPath: '/semester/add'
      preLoaderRoute: typeof SemesterAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/staff/add/': {
      id: '/staff/add/'
      path: '/staff/add'
      fullPath: '/staff/add'
      preLoaderRoute: typeof StaffAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/students/add/': {
      id: '/students/add/'
      path: '/students/add'
      fullPath: '/students/add'
      preLoaderRoute: typeof StudentsAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/subjects/add/': {
      id: '/subjects/add/'
      path: '/subjects/add'
      fullPath: '/subjects/add'
      preLoaderRoute: typeof SubjectsAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/trusties/add/': {
      id: '/trusties/add/'
      path: '/trusties/add'
      fullPath: '/trusties/add'
      preLoaderRoute: typeof TrustiesAddIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsIndexRoute
  '/calender': typeof CalenderIndexRoute
  '/cashiers': typeof CashiersIndexRoute
  '/committee': typeof CommitteeIndexRoute
  '/complaints': typeof ComplaintsIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/divisions': typeof DivisionsIndexRoute
  '/events': typeof EventsIndexRoute
  '/institutes': typeof InstitutesIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/login': typeof LoginIndexRoute
  '/meetings': typeof MeetingsIndexRoute
  '/memberdashboard': typeof MemberdashboardIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/rootdashboard': typeof RootdashboardIndexRoute
  '/semester': typeof SemesterIndexRoute
  '/staff': typeof StaffIndexRoute
  '/staffdashboard': typeof StaffdashboardIndexRoute
  '/students': typeof StudentsIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/trusties': typeof TrustiesIndexRoute
  '/admissions/edit/$id': typeof AdmissionsEditIdRoute
  '/cashiers/edit/$id': typeof CashiersEditIdRoute
  '/committee/edit/$id': typeof CommitteeEditIdRoute
  '/complaints/edit/$id': typeof ComplaintsEditIdRoute
  '/courses/edit/$id': typeof CoursesEditIdRoute
  '/divisions/edit/$id': typeof DivisionsEditIdRoute
  '/events/edit/$id': typeof EventsEditIdRoute
  '/institutes/edit/$id': typeof InstitutesEditIdRoute
  '/inventory/edit/$id': typeof InventoryEditIdRoute
  '/meetings/edit/$id': typeof MeetingsEditIdRoute
  '/rooms/edit/$id': typeof RoomsEditIdRoute
  '/semester/edit/$id': typeof SemesterEditIdRoute
  '/staff/edit/$id': typeof StaffEditIdRoute
  '/students/edit/$id': typeof StudentsEditIdRoute
  '/subjects/edit/$id': typeof SubjectsEditIdRoute
  '/trusties/edit/$id': typeof TrustiesEditIdRoute
  '/admissions/add': typeof AdmissionsAddIndexRoute
  '/cashiers/add': typeof CashiersAddIndexRoute
  '/committee/add': typeof CommitteeAddIndexRoute
  '/complaints/add': typeof ComplaintsAddIndexRoute
  '/courses/add': typeof CoursesAddIndexRoute
  '/divisions/add': typeof DivisionsAddIndexRoute
  '/events/add': typeof EventsAddIndexRoute
  '/institutes/add': typeof InstitutesAddIndexRoute
  '/inventory/add': typeof InventoryAddIndexRoute
  '/meetings/add': typeof MeetingsAddIndexRoute
  '/rooms/add': typeof RoomsAddIndexRoute
  '/semester/add': typeof SemesterAddIndexRoute
  '/staff/add': typeof StaffAddIndexRoute
  '/students/add': typeof StudentsAddIndexRoute
  '/subjects/add': typeof SubjectsAddIndexRoute
  '/trusties/add': typeof TrustiesAddIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsIndexRoute
  '/calender': typeof CalenderIndexRoute
  '/cashiers': typeof CashiersIndexRoute
  '/committee': typeof CommitteeIndexRoute
  '/complaints': typeof ComplaintsIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/divisions': typeof DivisionsIndexRoute
  '/events': typeof EventsIndexRoute
  '/institutes': typeof InstitutesIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/login': typeof LoginIndexRoute
  '/meetings': typeof MeetingsIndexRoute
  '/memberdashboard': typeof MemberdashboardIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/rootdashboard': typeof RootdashboardIndexRoute
  '/semester': typeof SemesterIndexRoute
  '/staff': typeof StaffIndexRoute
  '/staffdashboard': typeof StaffdashboardIndexRoute
  '/students': typeof StudentsIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/trusties': typeof TrustiesIndexRoute
  '/admissions/edit/$id': typeof AdmissionsEditIdRoute
  '/cashiers/edit/$id': typeof CashiersEditIdRoute
  '/committee/edit/$id': typeof CommitteeEditIdRoute
  '/complaints/edit/$id': typeof ComplaintsEditIdRoute
  '/courses/edit/$id': typeof CoursesEditIdRoute
  '/divisions/edit/$id': typeof DivisionsEditIdRoute
  '/events/edit/$id': typeof EventsEditIdRoute
  '/institutes/edit/$id': typeof InstitutesEditIdRoute
  '/inventory/edit/$id': typeof InventoryEditIdRoute
  '/meetings/edit/$id': typeof MeetingsEditIdRoute
  '/rooms/edit/$id': typeof RoomsEditIdRoute
  '/semester/edit/$id': typeof SemesterEditIdRoute
  '/staff/edit/$id': typeof StaffEditIdRoute
  '/students/edit/$id': typeof StudentsEditIdRoute
  '/subjects/edit/$id': typeof SubjectsEditIdRoute
  '/trusties/edit/$id': typeof TrustiesEditIdRoute
  '/admissions/add': typeof AdmissionsAddIndexRoute
  '/cashiers/add': typeof CashiersAddIndexRoute
  '/committee/add': typeof CommitteeAddIndexRoute
  '/complaints/add': typeof ComplaintsAddIndexRoute
  '/courses/add': typeof CoursesAddIndexRoute
  '/divisions/add': typeof DivisionsAddIndexRoute
  '/events/add': typeof EventsAddIndexRoute
  '/institutes/add': typeof InstitutesAddIndexRoute
  '/inventory/add': typeof InventoryAddIndexRoute
  '/meetings/add': typeof MeetingsAddIndexRoute
  '/rooms/add': typeof RoomsAddIndexRoute
  '/semester/add': typeof SemesterAddIndexRoute
  '/staff/add': typeof StaffAddIndexRoute
  '/students/add': typeof StudentsAddIndexRoute
  '/subjects/add': typeof SubjectsAddIndexRoute
  '/trusties/add': typeof TrustiesAddIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/calender/': typeof CalenderIndexRoute
  '/cashiers/': typeof CashiersIndexRoute
  '/committee/': typeof CommitteeIndexRoute
  '/complaints/': typeof ComplaintsIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/divisions/': typeof DivisionsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/institutes/': typeof InstitutesIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/login/': typeof LoginIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/memberdashboard/': typeof MemberdashboardIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/rootdashboard/': typeof RootdashboardIndexRoute
  '/semester/': typeof SemesterIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staffdashboard/': typeof StaffdashboardIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/trusties/': typeof TrustiesIndexRoute
  '/admissions/edit/$id': typeof AdmissionsEditIdRoute
  '/cashiers/edit/$id': typeof CashiersEditIdRoute
  '/committee/edit/$id': typeof CommitteeEditIdRoute
  '/complaints/edit/$id': typeof ComplaintsEditIdRoute
  '/courses/edit/$id': typeof CoursesEditIdRoute
  '/divisions/edit/$id': typeof DivisionsEditIdRoute
  '/events/edit/$id': typeof EventsEditIdRoute
  '/institutes/edit/$id': typeof InstitutesEditIdRoute
  '/inventory/edit/$id': typeof InventoryEditIdRoute
  '/meetings/edit/$id': typeof MeetingsEditIdRoute
  '/rooms/edit/$id': typeof RoomsEditIdRoute
  '/semester/edit/$id': typeof SemesterEditIdRoute
  '/staff/edit/$id': typeof StaffEditIdRoute
  '/students/edit/$id': typeof StudentsEditIdRoute
  '/subjects/edit/$id': typeof SubjectsEditIdRoute
  '/trusties/edit/$id': typeof TrustiesEditIdRoute
  '/admissions/add/': typeof AdmissionsAddIndexRoute
  '/cashiers/add/': typeof CashiersAddIndexRoute
  '/committee/add/': typeof CommitteeAddIndexRoute
  '/complaints/add/': typeof ComplaintsAddIndexRoute
  '/courses/add/': typeof CoursesAddIndexRoute
  '/divisions/add/': typeof DivisionsAddIndexRoute
  '/events/add/': typeof EventsAddIndexRoute
  '/institutes/add/': typeof InstitutesAddIndexRoute
  '/inventory/add/': typeof InventoryAddIndexRoute
  '/meetings/add/': typeof MeetingsAddIndexRoute
  '/rooms/add/': typeof RoomsAddIndexRoute
  '/semester/add/': typeof SemesterAddIndexRoute
  '/staff/add/': typeof StaffAddIndexRoute
  '/students/add/': typeof StudentsAddIndexRoute
  '/subjects/add/': typeof SubjectsAddIndexRoute
  '/trusties/add/': typeof TrustiesAddIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admissions'
    | '/calender'
    | '/cashiers'
    | '/committee'
    | '/complaints'
    | '/courses'
    | '/divisions'
    | '/events'
    | '/institutes'
    | '/inventory'
    | '/login'
    | '/meetings'
    | '/memberdashboard'
    | '/rooms'
    | '/rootdashboard'
    | '/semester'
    | '/staff'
    | '/staffdashboard'
    | '/students'
    | '/subjects'
    | '/trusties'
    | '/admissions/edit/$id'
    | '/cashiers/edit/$id'
    | '/committee/edit/$id'
    | '/complaints/edit/$id'
    | '/courses/edit/$id'
    | '/divisions/edit/$id'
    | '/events/edit/$id'
    | '/institutes/edit/$id'
    | '/inventory/edit/$id'
    | '/meetings/edit/$id'
    | '/rooms/edit/$id'
    | '/semester/edit/$id'
    | '/staff/edit/$id'
    | '/students/edit/$id'
    | '/subjects/edit/$id'
    | '/trusties/edit/$id'
    | '/admissions/add'
    | '/cashiers/add'
    | '/committee/add'
    | '/complaints/add'
    | '/courses/add'
    | '/divisions/add'
    | '/events/add'
    | '/institutes/add'
    | '/inventory/add'
    | '/meetings/add'
    | '/rooms/add'
    | '/semester/add'
    | '/staff/add'
    | '/students/add'
    | '/subjects/add'
    | '/trusties/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admissions'
    | '/calender'
    | '/cashiers'
    | '/committee'
    | '/complaints'
    | '/courses'
    | '/divisions'
    | '/events'
    | '/institutes'
    | '/inventory'
    | '/login'
    | '/meetings'
    | '/memberdashboard'
    | '/rooms'
    | '/rootdashboard'
    | '/semester'
    | '/staff'
    | '/staffdashboard'
    | '/students'
    | '/subjects'
    | '/trusties'
    | '/admissions/edit/$id'
    | '/cashiers/edit/$id'
    | '/committee/edit/$id'
    | '/complaints/edit/$id'
    | '/courses/edit/$id'
    | '/divisions/edit/$id'
    | '/events/edit/$id'
    | '/institutes/edit/$id'
    | '/inventory/edit/$id'
    | '/meetings/edit/$id'
    | '/rooms/edit/$id'
    | '/semester/edit/$id'
    | '/staff/edit/$id'
    | '/students/edit/$id'
    | '/subjects/edit/$id'
    | '/trusties/edit/$id'
    | '/admissions/add'
    | '/cashiers/add'
    | '/committee/add'
    | '/complaints/add'
    | '/courses/add'
    | '/divisions/add'
    | '/events/add'
    | '/institutes/add'
    | '/inventory/add'
    | '/meetings/add'
    | '/rooms/add'
    | '/semester/add'
    | '/staff/add'
    | '/students/add'
    | '/subjects/add'
    | '/trusties/add'
  id:
    | '__root__'
    | '/'
    | '/admissions/'
    | '/calender/'
    | '/cashiers/'
    | '/committee/'
    | '/complaints/'
    | '/courses/'
    | '/divisions/'
    | '/events/'
    | '/institutes/'
    | '/inventory/'
    | '/login/'
    | '/meetings/'
    | '/memberdashboard/'
    | '/rooms/'
    | '/rootdashboard/'
    | '/semester/'
    | '/staff/'
    | '/staffdashboard/'
    | '/students/'
    | '/subjects/'
    | '/trusties/'
    | '/admissions/edit/$id'
    | '/cashiers/edit/$id'
    | '/committee/edit/$id'
    | '/complaints/edit/$id'
    | '/courses/edit/$id'
    | '/divisions/edit/$id'
    | '/events/edit/$id'
    | '/institutes/edit/$id'
    | '/inventory/edit/$id'
    | '/meetings/edit/$id'
    | '/rooms/edit/$id'
    | '/semester/edit/$id'
    | '/staff/edit/$id'
    | '/students/edit/$id'
    | '/subjects/edit/$id'
    | '/trusties/edit/$id'
    | '/admissions/add/'
    | '/cashiers/add/'
    | '/committee/add/'
    | '/complaints/add/'
    | '/courses/add/'
    | '/divisions/add/'
    | '/events/add/'
    | '/institutes/add/'
    | '/inventory/add/'
    | '/meetings/add/'
    | '/rooms/add/'
    | '/semester/add/'
    | '/staff/add/'
    | '/students/add/'
    | '/subjects/add/'
    | '/trusties/add/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissionsIndexRoute: typeof AdmissionsIndexRoute
  CalenderIndexRoute: typeof CalenderIndexRoute
  CashiersIndexRoute: typeof CashiersIndexRoute
  CommitteeIndexRoute: typeof CommitteeIndexRoute
  ComplaintsIndexRoute: typeof ComplaintsIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  DivisionsIndexRoute: typeof DivisionsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  InstitutesIndexRoute: typeof InstitutesIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MeetingsIndexRoute: typeof MeetingsIndexRoute
  MemberdashboardIndexRoute: typeof MemberdashboardIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  RootdashboardIndexRoute: typeof RootdashboardIndexRoute
  SemesterIndexRoute: typeof SemesterIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffdashboardIndexRoute: typeof StaffdashboardIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  TrustiesIndexRoute: typeof TrustiesIndexRoute
  AdmissionsEditIdRoute: typeof AdmissionsEditIdRoute
  CashiersEditIdRoute: typeof CashiersEditIdRoute
  CommitteeEditIdRoute: typeof CommitteeEditIdRoute
  ComplaintsEditIdRoute: typeof ComplaintsEditIdRoute
  CoursesEditIdRoute: typeof CoursesEditIdRoute
  DivisionsEditIdRoute: typeof DivisionsEditIdRoute
  EventsEditIdRoute: typeof EventsEditIdRoute
  InstitutesEditIdRoute: typeof InstitutesEditIdRoute
  InventoryEditIdRoute: typeof InventoryEditIdRoute
  MeetingsEditIdRoute: typeof MeetingsEditIdRoute
  RoomsEditIdRoute: typeof RoomsEditIdRoute
  SemesterEditIdRoute: typeof SemesterEditIdRoute
  StaffEditIdRoute: typeof StaffEditIdRoute
  StudentsEditIdRoute: typeof StudentsEditIdRoute
  SubjectsEditIdRoute: typeof SubjectsEditIdRoute
  TrustiesEditIdRoute: typeof TrustiesEditIdRoute
  AdmissionsAddIndexRoute: typeof AdmissionsAddIndexRoute
  CashiersAddIndexRoute: typeof CashiersAddIndexRoute
  CommitteeAddIndexRoute: typeof CommitteeAddIndexRoute
  ComplaintsAddIndexRoute: typeof ComplaintsAddIndexRoute
  CoursesAddIndexRoute: typeof CoursesAddIndexRoute
  DivisionsAddIndexRoute: typeof DivisionsAddIndexRoute
  EventsAddIndexRoute: typeof EventsAddIndexRoute
  InstitutesAddIndexRoute: typeof InstitutesAddIndexRoute
  InventoryAddIndexRoute: typeof InventoryAddIndexRoute
  MeetingsAddIndexRoute: typeof MeetingsAddIndexRoute
  RoomsAddIndexRoute: typeof RoomsAddIndexRoute
  SemesterAddIndexRoute: typeof SemesterAddIndexRoute
  StaffAddIndexRoute: typeof StaffAddIndexRoute
  StudentsAddIndexRoute: typeof StudentsAddIndexRoute
  SubjectsAddIndexRoute: typeof SubjectsAddIndexRoute
  TrustiesAddIndexRoute: typeof TrustiesAddIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissionsIndexRoute: AdmissionsIndexRoute,
  CalenderIndexRoute: CalenderIndexRoute,
  CashiersIndexRoute: CashiersIndexRoute,
  CommitteeIndexRoute: CommitteeIndexRoute,
  ComplaintsIndexRoute: ComplaintsIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  DivisionsIndexRoute: DivisionsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  InstitutesIndexRoute: InstitutesIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MeetingsIndexRoute: MeetingsIndexRoute,
  MemberdashboardIndexRoute: MemberdashboardIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  RootdashboardIndexRoute: RootdashboardIndexRoute,
  SemesterIndexRoute: SemesterIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffdashboardIndexRoute: StaffdashboardIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  TrustiesIndexRoute: TrustiesIndexRoute,
  AdmissionsEditIdRoute: AdmissionsEditIdRoute,
  CashiersEditIdRoute: CashiersEditIdRoute,
  CommitteeEditIdRoute: CommitteeEditIdRoute,
  ComplaintsEditIdRoute: ComplaintsEditIdRoute,
  CoursesEditIdRoute: CoursesEditIdRoute,
  DivisionsEditIdRoute: DivisionsEditIdRoute,
  EventsEditIdRoute: EventsEditIdRoute,
  InstitutesEditIdRoute: InstitutesEditIdRoute,
  InventoryEditIdRoute: InventoryEditIdRoute,
  MeetingsEditIdRoute: MeetingsEditIdRoute,
  RoomsEditIdRoute: RoomsEditIdRoute,
  SemesterEditIdRoute: SemesterEditIdRoute,
  StaffEditIdRoute: StaffEditIdRoute,
  StudentsEditIdRoute: StudentsEditIdRoute,
  SubjectsEditIdRoute: SubjectsEditIdRoute,
  TrustiesEditIdRoute: TrustiesEditIdRoute,
  AdmissionsAddIndexRoute: AdmissionsAddIndexRoute,
  CashiersAddIndexRoute: CashiersAddIndexRoute,
  CommitteeAddIndexRoute: CommitteeAddIndexRoute,
  ComplaintsAddIndexRoute: ComplaintsAddIndexRoute,
  CoursesAddIndexRoute: CoursesAddIndexRoute,
  DivisionsAddIndexRoute: DivisionsAddIndexRoute,
  EventsAddIndexRoute: EventsAddIndexRoute,
  InstitutesAddIndexRoute: InstitutesAddIndexRoute,
  InventoryAddIndexRoute: InventoryAddIndexRoute,
  MeetingsAddIndexRoute: MeetingsAddIndexRoute,
  RoomsAddIndexRoute: RoomsAddIndexRoute,
  SemesterAddIndexRoute: SemesterAddIndexRoute,
  StaffAddIndexRoute: StaffAddIndexRoute,
  StudentsAddIndexRoute: StudentsAddIndexRoute,
  SubjectsAddIndexRoute: SubjectsAddIndexRoute,
  TrustiesAddIndexRoute: TrustiesAddIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admissions/",
        "/calender/",
        "/cashiers/",
        "/committee/",
        "/complaints/",
        "/courses/",
        "/divisions/",
        "/events/",
        "/institutes/",
        "/inventory/",
        "/login/",
        "/meetings/",
        "/memberdashboard/",
        "/rooms/",
        "/rootdashboard/",
        "/semester/",
        "/staff/",
        "/staffdashboard/",
        "/students/",
        "/subjects/",
        "/trusties/",
        "/admissions/edit/$id",
        "/cashiers/edit/$id",
        "/committee/edit/$id",
        "/complaints/edit/$id",
        "/courses/edit/$id",
        "/divisions/edit/$id",
        "/events/edit/$id",
        "/institutes/edit/$id",
        "/inventory/edit/$id",
        "/meetings/edit/$id",
        "/rooms/edit/$id",
        "/semester/edit/$id",
        "/staff/edit/$id",
        "/students/edit/$id",
        "/subjects/edit/$id",
        "/trusties/edit/$id",
        "/admissions/add/",
        "/cashiers/add/",
        "/committee/add/",
        "/complaints/add/",
        "/courses/add/",
        "/divisions/add/",
        "/events/add/",
        "/institutes/add/",
        "/inventory/add/",
        "/meetings/add/",
        "/rooms/add/",
        "/semester/add/",
        "/staff/add/",
        "/students/add/",
        "/subjects/add/",
        "/trusties/add/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admissions/": {
      "filePath": "admissions/index.tsx"
    },
    "/calender/": {
      "filePath": "calender/index.tsx"
    },
    "/cashiers/": {
      "filePath": "cashiers/index.tsx"
    },
    "/committee/": {
      "filePath": "committee/index.tsx"
    },
    "/complaints/": {
      "filePath": "complaints/index.tsx"
    },
    "/courses/": {
      "filePath": "courses/index.tsx"
    },
    "/divisions/": {
      "filePath": "divisions/index.tsx"
    },
    "/events/": {
      "filePath": "events/index.tsx"
    },
    "/institutes/": {
      "filePath": "institutes/index.tsx"
    },
    "/inventory/": {
      "filePath": "inventory/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/meetings/": {
      "filePath": "meetings/index.tsx"
    },
    "/memberdashboard/": {
      "filePath": "memberdashboard/index.tsx"
    },
    "/rooms/": {
      "filePath": "rooms/index.tsx"
    },
    "/rootdashboard/": {
      "filePath": "rootdashboard/index.tsx"
    },
    "/semester/": {
      "filePath": "semester/index.tsx"
    },
    "/staff/": {
      "filePath": "staff/index.tsx"
    },
    "/staffdashboard/": {
      "filePath": "staffdashboard/index.tsx"
    },
    "/students/": {
      "filePath": "students/index.tsx"
    },
    "/subjects/": {
      "filePath": "subjects/index.tsx"
    },
    "/trusties/": {
      "filePath": "trusties/index.tsx"
    },
    "/admissions/edit/$id": {
      "filePath": "admissions/edit/$id.tsx"
    },
    "/cashiers/edit/$id": {
      "filePath": "cashiers/edit/$id.tsx"
    },
    "/committee/edit/$id": {
      "filePath": "committee/edit/$id.tsx"
    },
    "/complaints/edit/$id": {
      "filePath": "complaints/edit/$id.tsx"
    },
    "/courses/edit/$id": {
      "filePath": "courses/edit/$id.tsx"
    },
    "/divisions/edit/$id": {
      "filePath": "divisions/edit/$id.tsx"
    },
    "/events/edit/$id": {
      "filePath": "events/edit/$id.tsx"
    },
    "/institutes/edit/$id": {
      "filePath": "institutes/edit/$id.tsx"
    },
    "/inventory/edit/$id": {
      "filePath": "inventory/edit/$id.tsx"
    },
    "/meetings/edit/$id": {
      "filePath": "meetings/edit/$id.tsx"
    },
    "/rooms/edit/$id": {
      "filePath": "rooms/edit/$id.tsx"
    },
    "/semester/edit/$id": {
      "filePath": "semester/edit/$id.tsx"
    },
    "/staff/edit/$id": {
      "filePath": "staff/edit/$id.tsx"
    },
    "/students/edit/$id": {
      "filePath": "students/edit/$id.tsx"
    },
    "/subjects/edit/$id": {
      "filePath": "subjects/edit/$id.tsx"
    },
    "/trusties/edit/$id": {
      "filePath": "trusties/edit/$id.tsx"
    },
    "/admissions/add/": {
      "filePath": "admissions/add/index.tsx"
    },
    "/cashiers/add/": {
      "filePath": "cashiers/add/index.tsx"
    },
    "/committee/add/": {
      "filePath": "committee/add/index.tsx"
    },
    "/complaints/add/": {
      "filePath": "complaints/add/index.tsx"
    },
    "/courses/add/": {
      "filePath": "courses/add/index.tsx"
    },
    "/divisions/add/": {
      "filePath": "divisions/add/index.tsx"
    },
    "/events/add/": {
      "filePath": "events/add/index.tsx"
    },
    "/institutes/add/": {
      "filePath": "institutes/add/index.tsx"
    },
    "/inventory/add/": {
      "filePath": "inventory/add/index.tsx"
    },
    "/meetings/add/": {
      "filePath": "meetings/add/index.tsx"
    },
    "/rooms/add/": {
      "filePath": "rooms/add/index.tsx"
    },
    "/semester/add/": {
      "filePath": "semester/add/index.tsx"
    },
    "/staff/add/": {
      "filePath": "staff/add/index.tsx"
    },
    "/students/add/": {
      "filePath": "students/add/index.tsx"
    },
    "/subjects/add/": {
      "filePath": "subjects/add/index.tsx"
    },
    "/trusties/add/": {
      "filePath": "trusties/add/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
